### PR TITLE
Add Nextflow

### PR DESCRIPTION
**Pull request by whoisteve**

### CODE REVIEW

**Comment by BonaBeavis** [comment]
There is a misunderstanding, the rml editor should not run ontoflow but this [nextflow](https://gitlab.com/kupferdigital/data-ecosystem/workflows/workflow-template) workflow.

Here a rough outline:

1. Starting point:
    - Nextflow is installed
    - https://gitlab.com/kupferdigital/data-ecosystem/workflows/workflow-template is cloned
 
2. Now the plugin should:
    1. Display those files on the left: https://gitlab.com/kupferdigital/data-ecosystem/workflows/workflow-template/-/tree/main/files/data
    2. The mapping file in the middle: https://gitlab.com/kupferdigital/data-ecosystem/workflows/workflow-template/-/tree/main/files/mapping
    3. And a output window on the right.

3. A button for triggering something like:  `nextflow run -params-file config.json https://gitlab.com/kupferdigital/data-ecosystem/workflows/workflow-template -r main` And the result should appear in the right output window.

**Comment by BonaBeavis** [comment]
Can you update the readme with install instructions, so I can test the plugin?

**Comment by stevomat** [comment]
What should I exactly update? To test the plugin you only need Java and docker to be installed. Also, you can clone my repository `git clone git@github.com:stevomat/rml-editor.git` in `~/.atom/packages/` to test the plugin. Therefore delete your existing rml-editor package and reload Atom.

**Comment by BonaBeavis** [comment]
Think of someone who has a naked fresh ubuntu box and who wants to try out the rml-editor. So it should also be included how to install atom. You can use this https://gitlab.com/kupferdigital/ontoflow#installation

**Comment by stevomat** [comment]
I updated the readme with install detailed install instructions and updated the keymap-look.

**Pull request closed without merging**
